#!/bin/sh
while read host
do
	{ error=$( { curl -IL --no-progress-meter -o /dev/null --write-out '%{http_code}' "$host" 1>&3 ; } 2>&1); } 3>&1
	printf "\t%s\t%s\n" "$host" "$error"
done < ${host:-/dev/stdin}
