#!/bin/sh
# take a list of servers and probe for working http[s]
result=$(xargs -n1 -P5 curl --connect-timeout 3 -sLI -o /dev/null --write-out '%{http_code}\t%{url_effective}\n' < /dev/stdin)
case $1 in
	-v) echo "$result";;
	*) echo "$result" | awk '{if($1 == "200"){print $2}}';;
esac
